📦 Phase 1.2: NumPy (Numerical Python)
🔍 Why it matters:
Backbone of ML/AI: fast array operations, math, and matrix ops

Used in nearly every AI pipeline (especially with vectors & tensors)

✅ NumPy Core Concepts Checklist:
Concept	Why It Matters
np.array	Create arrays (1D, 2D, ND)
Indexing/Slicing	Access & manipulate data
Array Math (add, mult, etc)	Efficient vectorized computation
Shape, Reshape, Flatten	Manage tensor shapes (important for models)
Broadcasting	Auto-matching shapes in math ops
Random module	Generate data / test data
Axis & Aggregations	Sum, mean, etc. across rows/columns

In [ ]:
#create array
import numpy as np

arr_1d = np.array([1, 2, 3])
arr_2d = np.array([[3, 4], [5, 6]])

a = np.array([2, 3])
b=np.array([1, 2, 3])

print(arr_1d)
print(arr_2d)

[1 2 3]
[[3 4]
 [5 6]]


In [21]:
#index slicing
print(arr_2d[0][1])
print(arr_1d[:2])
print(arr_2d[1:, 1:])
print(arr_2d[:,0])

4
[1 2]
[[6]]
[3 5]


In [22]:
#math
print(arr_1d + b)
print(arr_1d * b)

[2 4 6]
[1 4 9]


In [23]:
#broadcasting
print(arr_2d+ a)

[[5 7]
 [7 9]]


In [ ]:
#method
print(np.sum(arr_2d))
print(np.mean(arr_2d))

print(arr_2d.shape)
print(arr_2d.dtype)
print(arr_2d.reshape(4, 1))
print(arr_2d.flatten())

18
4.5
(2, 2)
int64
[[3]
 [4]
 [5]
 [6]]
[3 4 5 6]


In [25]:
#generate data
np.zeros((2, 3))  
print(np.zeros((2,3)))
print(np.ones((2,3)))
print(np.random.rand(2,3))
print(np.random.randn(3,3)) #normal distribution float values
print(np.random.randint(0,10, size=(2,2)))

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[0.45881033 0.16526211 0.47054054]
 [0.89370606 0.82776201 0.8738129 ]]
[[ 0.11605705  0.47561646 -1.1488125 ]
 [-0.39343248  0.34704373 -0.33473023]
 [-0.7548672  -0.21132304  0.19933317]]
[[9 9]
 [1 9]]


In [27]:
#axis aggregation
print(np.sum(arr_2d, axis=0))
print(np.sum(arr_2d, axis=1))
print(np.mean(arr_2d, axis=0))
print(np.mean(arr_2d, axis=1))

[ 8 10]
[ 7 11]
[4. 5.]
[3.5 5.5]


In [28]:
#combine everything
a = np.random.randint(1, 10, (3, 3))
print("Matrix:\n", a)
print("Slice center:", a[1:, 1:])
print("Sum across rows:", np.sum(a, axis=1))
print("Sum across cols:", np.sum(a, axis=0))

b = np.array([1, 2, 3])
print("Broadcast result:\n", a + b)


Matrix:
 [[5 5 8]
 [8 2 6]
 [3 7 5]]
Slice center: [[2 6]
 [7 5]]
Sum across rows: [18 16 15]
Sum across cols: [16 14 19]
Broadcast result:
 [[ 6  7 11]
 [ 9  4  9]
 [ 4  9  8]]


In [34]:
#matrix calculator
x = np.random.randint(1, 10, size=(2, 2))
y = np.random.randint(1, 10, size=(2, 2))
print(x)
print(y)

#add
print(x+y)

#substract
print(x-y)

#multiply
print(x*y)

#transpose
print(np.transpose(x))

# Inverse (only if matrix is invertible)
try:
    inverse_x = np.linalg.inv(x)
    print("\nInverse of X:\n", inverse_x)
except np.linalg.LinAlgError:
    print("\nX is not invertible.")

[[7 5]
 [1 7]]
[[9 5]
 [7 5]]
[[16 10]
 [ 8 12]]
[[-2  0]
 [-6  2]]
[[63 25]
 [ 7 35]]
[[7 1]
 [5 7]]

Inverse of X:
 [[ 0.15909091 -0.11363636]
 [-0.02272727  0.15909091]]
